development: 
  adapter: postgresql
  encoding: unicode
  database: taskrpg_development
  pool: 5
  timeout: 5000
  socket: /var/pgsql_socket

test:
  adapter: postgresql
  encoding: unicode
  database: taskrpg_test
  pool: 5
  timeout: 5000
  socket: /var/pgsql_socket

production:
  adapter: postgresql
  encoding: unicode
  database: taskrpg_production
  pool: 5
  timeout: 5000

